services:
  - type: web
    name: django-web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-db
          property: connectionString
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: false
      - key: REDIS_URL
        value: redis://...

  - type: worker
    name: celery-worker
    env: python
    startCommand: celery -A myproject worker --loglevel=info
    envVars:
      - fromService:
          type: web
          name: django-web

  - type: worker
    name: celery-beat
    env: python
    startCommand: celery -A myproject beat --loglevel=info
    envVars:
      - fromService:
          type: web
          name: django-web

databases:
  - name: my-db
    plan: free
